### ISSUE TITLE
Human slowed in own grenade

### ISSUE THREAD

**Issue by LordRofl** [AgentWesker/ZR_Tagging#1]
I'm also slowed in my own molotov/incgrenade fire as Human.
Is that on purpose? I'd like to have it not affect the Humans at all.

**Comment by AgentWesker** [comment]
Do you take any damage from the fire? Normally ZR should block damage from molotovs, which would mean the tagging won't trigger. Even if you do take damage though, there is a check that should only slow zombies (ZR_IsClientZombie)

**Comment by LordRofl** [comment]
Humans not take any damage from fire but slowed down. I fixed it already for myself in your code.

**Comment by AgentWesker** [comment]
Mind posting the fix?
